# https://github.com/ros-controls/ros2_controllers/

controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    omni_wheel_drive_controller:
      type: omni_wheel_drive_controller/OmniWheelDriveController

omni_wheel_drive_controller:
  ros__parameters:
    wheel_names: ["mx3_wheel3_Joint", "mx1_wheel1_Joint", "mx2_wheel2_Joint"]
    
    wheel_offset: 0.0

    robot_radius: 0.090
    wheel_radius: 0.025

    odom_frame_id: "odom"
    base_frame_id: "base_footprint"

    enable_odom_tf: true

    diagonal_covariance:
      pose: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
      twist: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]