<?xml version="1.0"?>

<robot name="mobilebot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- xacro includes -->
    <xacro:include filename="common_properties.xacro"/>
    <xacro:include filename="mobilebot_base.xacro"/>
    <!-- <xacro:include filename="mobilebot_base_gazebo.xacro"/>
    <xacro:include filename="arm.xacro"/>
    <xacro:include filename="arm_gazebo.xacro"/> -->
    <xacro:include filename="mobilebot_base.ros2_control.xacro"/>

    <!-- #### Combine the robot(mobilebot) and arm #### -->
    <!-- <joint name="mobilebot_base_arm_joint" type="fixed">
        <parent link="base_link"/>
        <child link="arm_base_link"/>
        <origin xyz="${base_length/4} 0 ${base_height}" rpy="0 0 0"/>
    </joint> -->
</robot>