<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- #### ##### xacro defines ##### #### -->
    <xacro:property name="PI"               value="3.14159"/>
    <xacro:property name="arm_base_length"  value="0.1"/>
    <xacro:property name="arm_base_width"   value="0.1"/>
    <xacro:property name="arm_base_height"  value="0.02"/>
    <xacro:property name="forearm_radius"   value="0.02"/>
    <xacro:property name="forearm_length"   value="0.3"/>
    <xacro:property name="hand_radius"      value="0.02"/>
    <xacro:property name="hand_length"      value="0.3"/>

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"/>
            </geometry>
            <origin xyz="0 0 ${arm_base_height/2}" rpy="0 0 0"/>
            <material name="orange"/>
        </visual> 
        <collision>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"/>
            </geometry>
            <origin xyz="0 0 ${arm_base_height/2}" rpy="0 0 0"/>            
        </collision>
        <xacro:box_inertia mass="0.3" length="${arm_base_length}" width="${arm_base_width}" height="${arm_base_height}"
                           xyz="0 0 ${arm_base_height/2}" rpy="0 0 0"/>
    </link>

    <link name="forearm_link">
        <visual>
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}"/>
            </geometry>
            <origin xyz="0 0 ${forearm_length/2}" rpy="0 0 0"/>
            <material name="green"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}"/>
            </geometry>
            <origin xyz="0 0 ${forearm_length/2}" rpy="0 0 0"/>            
        </collision>
        <xacro:cylinder_inertia mass="0.2" radius="${forearm_radius}" height="${forearm_length}"
                           xyz="0 0 ${forearm_length/2}" rpy="0 0 0"/>
    </link>
    <joint name="arm_base_forearm_joint" type="revolute">
        <parent link="arm_base_link"/>
        <child link="forearm_link"/>
        <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="0" upper="${PI/2}" effort="100" velocity="100"/>
        <dynamics friction="0.05" damping="0.1"/>
    </joint>

    <link name="hand_link">
        <visual>
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}"/>
            </geometry>
            <origin xyz="0 0 ${hand_length/2}" rpy="0 0 0"/>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}"/>
            </geometry>
            <origin xyz="0 0 ${hand_length/2}" rpy="0 0 0"/>            
        </collision>
        <xacro:cylinder_inertia mass="0.2" radius="${hand_radius}" height="${hand_length}"
                           xyz="0 0 ${hand_length/2}" rpy="0 0 0"/>
    </link>
    <joint name="forearm_hand_joint" type="revolute">
        <parent link="forearm_link"/>
        <child link="hand_link"/>
        <origin xyz="0 0 ${forearm_length}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="0" upper="${PI/2}" effort="100" velocity="100"/>
        <dynamics friction="0.05" damping="0.1"/>
    </joint>

</robot>