<?xml version="1.0"?>
<robot name="mobilebot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="common_properties.xacro" />
    <xacro:include filename="mobilebot_base.xacro" />
    <xacro:include filename="arm.xacro"/>

    <joint name="mobilebot_base_arm_joint" type="fixed">
        <parent link="base_link" />
        <child link="arm_base_link" />
        <origin xyz="${base_length / 4.0} 0 ${base_height}" rpy="0 0 0" />
    </joint>

    <gazebo reference="caster_wheel_link">
        <mu1 value="0.1" />
        <mu2 value="0.1" />
    </gazebo>

    <ros2_control name="MyRobot" type="system">

        <hardware>
            <plugin>gz_ros2_control/GazeboSimSystem</plugin>
        </hardware>

        <joint name="base_RightWheel_joint">
            <command_interface name="velocity" />
            <state_interface name="position" />
            <state_interface name="velocity" />
        </joint>

        <joint name="base_LeftWheel_joint">
            <command_interface name="velocity" />
            <state_interface name="position" />
            <state_interface name="velocity" />
        </joint>

        <joint name="arm_base_forearm_joint">
            <command_interface name="position" />
            <state_interface name="position" />
        </joint>

        <joint name="forearm_hand_joint">
            <command_interface name="position" />
            <state_interface name="position" />
        </joint>

    </ros2_control>
    
    <gazebo>

        <plugin filename="gz_ros2_control-system" name="gz_ros2_control::GazeboSimROS2ControlPlugin">
            <parameters>$(find mobilebot_bringup)/config/mobilebot_controllers.yaml</parameters>
        </plugin>

    </gazebo>

</robot>