<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">   
<!-- ##################################################################################################### -->

    <xacro:macro name="kukabase" params="name">

        <link name="${name}_footprint">
            <visual>
                <geometry>
                    <box size="0.001 0.001 0.001"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <material name="Red"/>
            </visual>

            <collision>
                <geometry>
                    <box size="0.001 0.001 0.001"/>
                </geometry>
                <origin xyz="0 0 ${-base_size_z / 2.0}" rpy="0 0 0"/>
            </collision>
            <inertial>
                <mass value="0.1"/>
                <origin xyz="0 0 ${-base_size_z / 2.0}" rpy="0 0 0"/>
                <inertia ixx="1.0" ixy="0.0" ixz="0.0" 
                         iyy="1.0" iyz="0.0" 
                         izz="1.0"/>
            </inertial>
        </link>

        <joint name="${name}_footprint_joint" type="fixed">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <child link="${name}_link"/>
            <parent link="${name}_footprint"/>
        </joint>

        <link name="${name}_link">
            <visual>
                <geometry>
                    <mesh filename="package://kukabot_description/meshes/base/base.dae"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <material name="DarkGrey"/>
            </visual>

            <collision>
                <geometry>
                    <!--<box size="${base_size_x} ${base_size_y} ${base_size_z}" />-->
                    <mesh filename="package://kukabot_description/meshes/base/base_convex.dae"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </collision>            
            <inertial>
                <mass value="${base_mass}"/>
                <origin xyz="0 0 0"/>
                <inertia ixx="5.652232699207" ixy="-0.009719934438" ixz="1.293988226423" 
                         iyy="5.669473158652" iyz="-0.007379583694" 
                         izz="3.683196351726"/>
            </inertial>
        </link>

    </xacro:macro>
    
</robot>